name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run suggest_subword_sizes.sh
        run: |
          set -e -o xtrace
          RESULT="$(./suggest_subword_sizes.sh en de cs it)"
          grep -qF 'Suggested subword sizes for en: -minn 1 -maxn 5' <<< "$RESULT"
          grep -qF 'Suggested subword sizes for de: -minn 6 -maxn 6' <<< "$RESULT"
          grep -qF 'Suggested subword sizes for cs: -minn 1 -maxn 4' <<< "$RESULT"
          grep -qF 'Suggested subword sizes for it: -minn 6 -maxn 6' <<< "$RESULT"
